%% Project 13: 3D CAD Multi-Axis Attitude Control Simulation


%% 0. Load Simscape Multibody CAD Parameters (Critical Fix)
if exist('Assem3_DataFile.m', 'file')
    Assem2_DataFile;
else
    dataFile = dir('*_DataFile.m');
    if ~isempty(dataFile)
        run(dataFile(1).name);
    else
        error('smiData not found! Please run the <YourModel>_DataFile.m generated by smimport.');
    end
end

%% 1. Plant Inertia & Damping Parameters (Black Hornet Nano)
I_roll  = 5.94e-5;    b_crit_roll  = 0.0154;
I_pitch = 2.76e-5;    b_crit_pitch = 0.0105;
I_yaw   = 8.70e-5;    b_crit_yaw   = 0.0187;
Ts = 0.001; % 1 kHz IMU sampling rate

%% 2. Discrete Kalman Filter Gain Synthesis (dlqe)
% --- Roll Axis Estimator ---
A_r = [0 1; 0 -b_crit_roll/I_roll];   B_r = [0; 1/I_roll];
sys_roll_d = c2d(ss(A_r, B_r, [1 0; 0 1], [0; 0]), Ts);
Ad_roll = sys_roll_d.A;  Bd_roll = sys_roll_d.B;  Cd_roll = sys_roll_d.C;
Q_roll  = diag([0.01, 0.8]);
R_roll  = diag([0.0268^2, 0.0436^2]);
[~, K_roll, ~] = dlqe(Ad_roll, eye(2), Cd_roll, Q_roll, R_roll);

% --- Pitch Axis Estimator ---
A_p = [0 1; 0 -b_crit_pitch/I_pitch]; B_p = [0; 1/I_pitch];
sys_pitch_d = c2d(ss(A_p, B_p, [1 0; 0 1], [0; 0]), Ts);
Ad_pitch = sys_pitch_d.A; Bd_pitch = sys_pitch_d.B; Cd_pitch = sys_pitch_d.C;
Q_pitch  = diag([0.01, 0.01]);
R_pitch  = diag([0.026881^2, 0.038771^2]);
[~, K_pitch, ~] = dlqe(Ad_pitch, eye(2), Cd_pitch, Q_pitch, R_pitch);

% --- Yaw Axis Estimator ---
A_y = [0 1; 0 -b_crit_yaw/I_yaw];     B_y = [0; 1/I_yaw];
sys_yaw_d = c2d(ss(A_y, B_y, [1 0; 0 1], [0; 0]), Ts);
Ad_yaw = sys_yaw_d.A;   Bd_yaw = sys_yaw_d.B;   Cd_yaw = sys_yaw_d.C;
Q_yaw  = diag([0.01, 0.8]);
R_yaw  = diag([0.026575^2, 0.040843^2]);
[~, K_yaw, ~] = dlqe(Ad_yaw, eye(2), Cd_yaw, Q_yaw, R_yaw);

%% 3. Model Configuration & Solver Setup
modelName = 'Simultaneous_Multi_Axis_Disturbance_model';
if ~bdIsLoaded(modelName)
    load_system(modelName);
end
set_param(modelName, 'SolverType', 'Variable-step');
set_param(modelName, 'Solver', 'ode15s');
set_param(modelName, 'MaxStep', '0.001');
set_param(modelName, 'StopTime', '2.0');

%% 4. Command Profiles & Disturbance Injection
% Set uncommanded channels strictly to 0
set_param([modelName '/r_phi'], 'Before', '0', 'After', '0', 'Time', '0');
set_param([modelName '/r_psi'], 'Before', '0', 'After', '0', 'Time', '0');

% --- TWO-STAGE FLIGHT PROFILE: Forward Dash -> Flare to Level Hover ---
pitch_dash_deg = 15.0;            % Initial forward tilt angle
pitch_flare_deg = 0.0;            % Return to level hover
flare_time = 1.2;                 % Time to level off (seconds)

cmd_dash_rad  = deg2rad(pitch_dash_deg);
cmd_flare_rad = deg2rad(pitch_flare_deg);

% Single-block two-stage command:
% t in [0, 1.2s) -> pitches down to 15 deg (accelerates forward)
% t >= 1.2s     -> flares back to 0 deg (decelerates to level hover)
set_param([modelName '/r_theta'], ...
    'Before', num2str(cmd_dash_rad), ...
    'After',  num2str(cmd_flare_rad), ...
    'Time',   num2str(flare_time));

% =========================================================================
% DISTURBANCE TORQUE SETUP (Mid-flight wind gust strike & recovery)
% =========================================================================
distStart    = 0.60;   % Strikes mid-flight at 0.60 s while cruising
pitchDistEnd = 0.75;   % 150 ms pulse width (visible to naked eye)
pitchAmp     = 0.006;  % Nose-down torque pulse

rollDistEnd  = 0.75;   rollAmp = 0.0;
yawDistEnd   = 0.75;   yawAmp  = 0.0;

set_param([modelName '/Roll Axis Dynamics/Step_ON'],   'Time', num2str(distStart),    'After', num2str(rollAmp));
set_param([modelName '/Roll Axis Dynamics/Step_OFF'],  'Time', num2str(rollDistEnd),  'After', num2str(-rollAmp));
set_param([modelName '/Pitch Axis Dynamics/Step_ON'],  'Time', num2str(distStart),    'After', num2str(pitchAmp));
set_param([modelName '/Pitch Axis Dynamics/Step_OFF'], 'Time', num2str(pitchDistEnd), 'After', num2str(-pitchAmp));
set_param([modelName '/Yaw Axis Dynamics/Step_ON'],    'Time', num2str(distStart),    'After', num2str(yawAmp));
set_param([modelName '/Yaw Axis Dynamics/Step_OFF'],   'Time', num2str(yawDistEnd),   'After', num2str(-yawAmp));

%% 5. Execute Simulation and Launch Mechanics Explorer
fprintf('Starting 3D CAD dynamic attitude simulation...\n');
simOut = sim(modelName);
fprintf('Simulation complete. Mechanics Explorer launched.\n');

%% 6. Post-Flight Tracking & Chatter Performance Analysis
axesLabels = {'Roll (\phi)', 'Pitch (\theta)', 'Yaw (\psi)'};
trueNames  = {'phi', 'theta', 'psi'};
estNames   = {'phi_est', 'theta_est', 'psi_est'};

figure('Name', 'CAD Attitude State Tracking (3D Visualized Run)', 'Position', [100, 100, 1200, 480]);

for i = 1:3
    trueData = evalin('base', trueNames{i});
    estData  = evalin('base', estNames{i});
    
    t_true = trueData.Time;
    y_true = rad2deg(trueData.Data(:));
    
    t_est  = estData.Time;
    y_est  = rad2deg(estData.Data(:));
    
    subplot(1, 3, i);
    plot(t_true, y_true, 'b', 'LineWidth', 1.6, 'DisplayName', 'True CAD Motion'); hold on;
    plot(t_est, y_est, 'r--', 'LineWidth', 1.2, 'DisplayName', 'Kalman Estimate');
    
    if strcmp(trueNames{i}, 'theta')
        % Generate two-stage reference profile for plotting
        ref_profile = zeros(size(t_true));
        ref_profile(t_true < flare_time) = pitch_dash_deg;
        ref_profile(t_true >= flare_time) = pitch_flare_deg;
        plot(t_true, ref_profile, 'k:', 'LineWidth', 1.3, 'DisplayName', 'Reference Profile');
        
        % Measure terminal hover steady-state error (1.5s - 2.0s)
        hover_idx = t_true >= 1.5;
        rms_hover = rms(y_true(hover_idx) - pitch_flare_deg);
        title_str = sprintf('%s: Flare RMS Error = %.3f deg', axesLabels{i}, rms_hover);
    else
        yline(0, 'k:', 'LineWidth', 1.2, 'DisplayName', 'Reference');
        tail_idx = t_true >= (pitchDistEnd + 0.05);
        rms_val = rms(y_true(tail_idx));
        title_str = sprintf('%s: Cross-Coupled RMS = %.3f deg', axesLabels{i}, rms_val);
    end
    
    xline(distStart, ':m', 'LineWidth', 1.2, 'DisplayName', 'Disturbance Start');
    xline(pitchDistEnd, ':k', 'LineWidth', 1.1, 'DisplayName', 'Disturbance End');
    xline(flare_time, '--g', 'LineWidth', 1.1, 'DisplayName', 'Flare to Hover');
    grid on;
    xlabel('Time (s)'); ylabel('Angle (deg)');
    title(title_str);
    legend('Location', 'best');
end